**I. Struktur Data**

**LISTS**

In [58]:
aList = ["John",33,"Toronto",True]
aList

['John', 33, 'Toronto', True]

In [59]:
type(aList)

list

In [61]:
bin_colors=['Red','Green','Blue','Yellow']

**Tuples**

In [63]:
bin_colors=('Red','Green','Blue','Yellow')
print(f"The second element of the tuple is {bin_colors[1]}")

The second element of the tuple is Green


In [64]:
print(f"The elemets after thrid element onward are {bin_colors[2:]}")

The elemets after thrid element onward are ('Blue', 'Yellow')


In [65]:
nested_tuple = (1,2,(100,200,300),6)
print(f"The maximum value of the inner tuple {max(nested_tuple[2])}")

The maximum value of the inner tuple 300


**Dictionary**

In [67]:
bin_colors ={
    "manual_color": "Yellow",
    "approved_color": "Green",
    "refused_color": "Red"
}
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Green', 'refused_color': 'Red'}


In [68]:
bin_colors.get('approved_color')

'Green'

In [69]:
bin_colors['approved_color']

'Green'

In [70]:
bin_colors['approved_color']="purple"
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'purple', 'refused_color': 'Red'}


**Sets**

In [71]:
green = {'grass','leaves'}
print(green)

{'leaves', 'grass'}


In [72]:
yellow = {'dandelions','fire hydrant','leaves'}
red = {'fire hydrant','blood','rose','leaves'}

In [73]:
print(f"The union of yellow and red sets is {yellow|red}")

The union of yellow and red sets is {'leaves', 'dandelions', 'rose', 'blood', 'fire hydrant'}


In [74]:
print(f"The intersaction of yellow and red is {yellow&red}")

The intersaction of yellow and red is {'leaves', 'fire hydrant'}


**DataFrame**

In [75]:
import pandas as pd
df = pd.DataFrame([
    ['1',"Fares", 32, True],
    ['2',"Elena", 23, False],
    ['3', "Steven", 40, True]])
df.columns = ['id', 'name', 'age', 'decision']
print(df)

  id    name  age  decision
0  1   Fares   32      True
1  2   Elena   23     False
2  3  Steven   40      True


**Column Selection**

In [76]:
df[['name','age']]

name  age
0   Fares   32
1   Elena   23
2  Steven   40

In [77]:
df.iloc[:,3]

0     True
1    False
2     True
Name: decision, dtype: bool

**Row Selection**

In [79]:
df.iloc[1:3,:]

id    name  age  decision
1  2   Elena   23     False
2  3  Steven   40      True

In [80]:
df[df.age>30]

id    name  age  decision
0  1   Fares   32      True
2  3  Steven   40      True

**Matrix**

In [81]:
import numpy as np
myMatrix = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])

In [82]:
print(myMatrix)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [83]:
print(type(myMatrix))

<class 'numpy.ndarray'>


In [84]:
myMatrix.transpose()

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

**Vector**

In [85]:
myVector = [22,33,44,55]
print(myVector)

[22, 33, 44, 55]


In [86]:
print(type(myVector))

<class 'list'>


In [87]:
myVector = np.array([22,33,44,55])
print(myVector)

[22 33 44 55]


In [88]:
print(type(myVector))

<class 'numpy.ndarray'>


**Stack**

In [116]:
class Stack:
    def __init__(self):
        self.items = []
    def isEmpty(self):
        return self.items == []
    def push(self, item):
        self.items.append(item)
    def pop(self):
        return self.items.pop()
    def peek(self):
        return self.items[len(self.items)-1]
    def size(self):
        return len(self.items)

**Populate the stack**

In [117]:
stack=Stack()
stack.push('Red')
stack.push('Green')
stack.push("Blue")
stack.push("Yellow")

**Pop**

In [118]:
stack.pop()

'Yellow'

In [119]:
stack.isEmpty()

False

In [120]:
colors = ['Red']

In [121]:
colors.append('Green')
colors.append('Yellow')
colors.append('Blue')

In [122]:
colors

['Red', 'Green', 'Yellow', 'Blue']

**Queue**

In [107]:
class Queue(object):
   def __init__(self):
      self.items =[]
   def isEmpty(self):
      return self.items ==[]
   def enqueue(self, item):
       self.items.insert(0,item)
   def dequeue(self):
      return len(self.items)
   def size(self):
      return len(self.items)

In [109]:
queue = Queue()

In [110]:
queue.enqueue('Red')

In [111]:
queue.enqueue('Green')

In [112]:
queue.enqueue('Blue')

In [113]:
queue.enqueue('Yellow')

In [114]:
print(f"Size of queue is {queue.size()}")

Size of queue is 4


In [115]:
print(queue.dequeue())

4
